language: go
sudo: false

#go_import_path: github.com/criteo-forks/azure_metrics_exporter

install: true
script:
- find . -type f \( -name "*go" -o -name ".promu.yml" \) | xargs sed 's|github.com/RobustPerception/azure_metrics_exporter|github.com/criteo-forks/azure_metrics_exporter|'
  -i
- export VERSION=$(echo $TRAVIS_TAG | sed 's/^v//')
- make format
- gofmt -s -w main.go
- make -j 3 multiarch
before_deploy:
  - echo "Deploying $VERSION to GitHub releases"
  - for d  in $(find ./pkg/bin -maxdepth 1 -mindepth 1 -type d | cut -d '/' -f4); do tar -czf azure_metrics_exporter-${VERSION}.${d}.tar.gz ./pkg/bin/${d}/azure_metrics_exporter* ; done

deploy:
  provider: releases
  api_key:
    secure: BEBiikwmD4Qt2W8Tan+TDIG/lnG3+jYLIDH7EC22jcOYZg5kCM4fErmGuU+BC4vhmiX2sD+CosKhvsikZk79Lgh93Zupfae1Jt77Q2YglU97XCyvND92S48eAkfXgyHrNIu22ab74mHygVFGC3u5Wr5n+tJ+Y5hc1O6jGTvtcsiFDYhDWdFz19d4j4SyXv/uR6rvcj3948ewDr4Jr/fezQce6SptLo7J/kU0nNAKQMJvpp12Aah+SGzdeIqXwyJvxp5pZ0sBJr9u0m53SEdZEriGayQXzHEtR/3920ovG0U3owhptWtGr37jOEzOJUjhagd0qflKBoNqVhNTwmawc0u5hRcU7hgKcZpu1MIv/SsZAeEW2HNrc6FILpuiDPFGxcKT0P692ywzfAihqRreUKbEgRRrsMH/toK8yQjKYJrX2GcSuq0iZyUtGCMFkPD+iMCEMxphU2Ye2cW+0q8KIywX1YBmQOBgZm9bcj0Y7ES8ZblbMfVrIzgr4s6siOTZy+zJ0gjddbpZNQrrypDffWgspWhJ5sTdwL4ebm4pao5uxcBeZqGzLgDwLM8gYJpsfBC6ysJKjjT/BVMZtZOG0j6gVHfc/yfc/YQg9KbOcZnETQyML0764bGqzP0ds7zu2t1DvC/qUCxfJ5+7xufhWkeZ48c2lNLUX4sboZglGlo=
  file_glob: true
  file: azure_metrics_exporter-*.tar.gz
  skip_cleanup: true
  on:
    repo: criteo-forks/azure_metrics_exporter
    tags: true

